// <auto-generated />
using System;
using CalorieTracker.Client;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CalorieTracker.Client.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20260329121634_MoveUserIdInProduct")]
    partial class MoveUserIdInProduct
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CalorieTracker.Client.Entities.ActivityLevel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActivityLevelName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<float>("ActivityLevelRate")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("ActivityLevels", (string)null);
                });

            modelBuilder.Entity("CalorieTracker.Client.Entities.DailyCalorieLimit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2026, 3, 29, 16, 16, 33, 851, DateTimeKind.Local).AddTicks(9353));

                    b.Property<short>("DailyLimit")
                        .HasColumnType("smallint");

                    b.Property<short>("RemainingLimit")
                        .HasColumnType("smallint");

                    b.Property<short>("UsedLimit")
                        .HasColumnType("smallint");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("DailyCalorieLimits", (string)null);
                });

            modelBuilder.Entity("CalorieTracker.Client.Entities.DailyNutrientsIntakeAmount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<short>("Carbs")
                        .HasColumnType("smallint");

                    b.Property<short>("Fat")
                        .HasColumnType("smallint");

                    b.Property<short>("Protein")
                        .HasColumnType("smallint");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("DailyNutrientsIntakeAmounts", (string)null);
                });

            modelBuilder.Entity("CalorieTracker.Client.Entities.FitnessGoal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("CarbsPercent")
                        .HasColumnType("tinyint");

                    b.Property<byte>("FatPercent")
                        .HasColumnType("tinyint");

                    b.Property<string>("GoalName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte>("ProteinPercent")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.ToTable("FitnessGoals", (string)null);
                });

            modelBuilder.Entity("CalorieTracker.Client.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<short>("CaloriesPerHundredGram")
                        .HasColumnType("smallint");

                    b.Property<float>("CarbsPerHundredGram")
                        .HasColumnType("real");

                    b.Property<float>("FatPerHundredGram")
                        .HasColumnType("real");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<float>("ProteinPerHundredGram")
                        .HasColumnType("real");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("VisibilityScope")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Products", (string)null);
                });

            modelBuilder.Entity("CalorieTracker.Client.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2026, 3, 29, 12, 16, 33, 852, DateTimeKind.Utc).AddTicks(6947));

                    b.Property<int>("RoleType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasAlternateKey("RoleType")
                        .HasName("UQ_Users_RoleType");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("CalorieTracker.Client.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2026, 3, 29, 12, 16, 33, 853, DateTimeKind.Utc).AddTicks(2689));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasAlternateKey("Email")
                        .HasName("UQ_Users_Email");

                    b.HasIndex("UserName");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("CalorieTracker.Client.Entities.UserData", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ActivityLevelId")
                        .HasMaxLength(256)
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("Age")
                        .HasColumnType("tinyint");

                    b.Property<Guid>("FitnessGoalId")
                        .HasMaxLength(256)
                        .HasColumnType("uniqueidentifier");

                    b.Property<short>("Height")
                        .HasColumnType("smallint");

                    b.Property<short>("Weight")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("ActivityLevelId");

                    b.HasIndex("FitnessGoalId");

                    b.ToTable("UserData", (string)null);
                });

            modelBuilder.Entity("CalorieTracker.Client.Entities.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("CalorieTracker.Client.Entities.DailyCalorieLimit", b =>
                {
                    b.HasOne("CalorieTracker.Client.Entities.User", "User")
                        .WithMany("DailyCalorieLimits")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CalorieTracker.Client.Entities.DailyNutrientsIntakeAmount", b =>
                {
                    b.HasOne("CalorieTracker.Client.Entities.User", "User")
                        .WithMany("DailyNutrientsIntakeAmounts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CalorieTracker.Client.Entities.Product", b =>
                {
                    b.HasOne("CalorieTracker.Client.Entities.User", "User")
                        .WithMany("Products")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CalorieTracker.Client.Entities.UserData", b =>
                {
                    b.HasOne("CalorieTracker.Client.Entities.ActivityLevel", "ActivityLevel")
                        .WithMany("UserDatas")
                        .HasForeignKey("ActivityLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CalorieTracker.Client.Entities.FitnessGoal", "FitnessGoal")
                        .WithMany("UserDatas")
                        .HasForeignKey("FitnessGoalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CalorieTracker.Client.Entities.User", "User")
                        .WithOne("UserData")
                        .HasForeignKey("CalorieTracker.Client.Entities.UserData", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActivityLevel");

                    b.Navigation("FitnessGoal");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CalorieTracker.Client.Entities.UserRole", b =>
                {
                    b.HasOne("CalorieTracker.Client.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CalorieTracker.Client.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CalorieTracker.Client.Entities.ActivityLevel", b =>
                {
                    b.Navigation("UserDatas");
                });

            modelBuilder.Entity("CalorieTracker.Client.Entities.FitnessGoal", b =>
                {
                    b.Navigation("UserDatas");
                });

            modelBuilder.Entity("CalorieTracker.Client.Entities.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("CalorieTracker.Client.Entities.User", b =>
                {
                    b.Navigation("DailyCalorieLimits");

                    b.Navigation("DailyNutrientsIntakeAmounts");

                    b.Navigation("Products");

                    b.Navigation("UserData")
                        .IsRequired();

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
