// <auto-generated />
using System;
using CalorieTracker.Client;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CalorieTracker.Client.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20260324163545_TestForeignKey2")]
    partial class TestForeignKey2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CalorieTracker.Client.Entities.ActivityLevel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActivityLevelName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("ActivityLevelRate")
                        .HasColumnType("FLOAT");

                    b.HasKey("Id");

                    b.ToTable("ActivityLevels", (string)null);
                });

            modelBuilder.Entity("CalorieTracker.Client.Entities.DailyCalorieLimit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<short>("DailyLimit")
                        .HasColumnType("smallint");

                    b.Property<short>("RemainingLimit")
                        .HasColumnType("SMALLINT");

                    b.Property<short>("UsedLimit")
                        .HasColumnType("SMALLINT");

                    b.HasKey("Id");

                    b.ToTable("DailyCalorieLimits", (string)null);
                });

            modelBuilder.Entity("CalorieTracker.Client.Entities.DailyNutrientsIntakeAmount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<short>("Carbs")
                        .HasColumnType("SMALLINT");

                    b.Property<short>("Fat")
                        .HasColumnType("SMALLINT");

                    b.Property<short>("Protein")
                        .HasColumnType("SMALLINT");

                    b.HasKey("Id");

                    b.ToTable("DailyNutrientsIntakeAmounts", (string)null);
                });

            modelBuilder.Entity("CalorieTracker.Client.Entities.FitnessGoal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GoalName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("GoalValue")
                        .HasColumnType("FLOAT");

                    b.HasKey("Id");

                    b.ToTable("FitnessGoals", (string)null);
                });

            modelBuilder.Entity("CalorieTracker.Client.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<short>("CaloriesPerHundredGram")
                        .HasColumnType("SMALLINT");

                    b.Property<double>("CarbsPerHundredGram")
                        .HasColumnType("FLOAT");

                    b.Property<double>("FatPerHundredGram")
                        .HasColumnType("FLOAT");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("ProteinPerHundredGram")
                        .HasColumnType("FLOAT");

                    b.Property<byte>("VisibilityScope")
                        .HasColumnType("TINYINT");

                    b.HasKey("Id");

                    b.ToTable("Products", (string)null);
                });

            modelBuilder.Entity("CalorieTracker.Client.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2026, 3, 24, 16, 35, 45, 315, DateTimeKind.Utc).AddTicks(667));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("CalorieTracker.Client.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2026, 3, 24, 16, 35, 45, 315, DateTimeKind.Utc).AddTicks(7394));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasAlternateKey("Email")
                        .HasName("UQ_Users_Email");

                    b.HasIndex("UserName");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("CalorieTracker.Client.Entities.UserData", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActivityLevel")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<byte>("Age")
                        .HasColumnType("TINYINT");

                    b.Property<string>("FitnessGoal")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<short>("Height")
                        .HasColumnType("SMALLINT");

                    b.Property<short>("Weight")
                        .HasColumnType("SMALLINT");

                    b.HasKey("Id");

                    b.ToTable("UserData", (string)null);
                });

            modelBuilder.Entity("CalorieTracker.Client.Entities.UserData", b =>
                {
                    b.HasOne("CalorieTracker.Client.Entities.User", "User")
                        .WithOne()
                        .HasForeignKey("CalorieTracker.Client.Entities.UserData", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
